config/routes.rb
Supertramp::Application.routes.draw do
  
  authenticated :user do
    root :to => 'themes#index'
  end


  resources :themes do
    resources :categories do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
    end

    resources :cards do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
      resources :content do
        match 'themes/:theme_id/cards/card_id/contents/:id' => 'contents#update', :via => :put, :as => :update_theme_card_contents
      end
    end

  end

    
    
    
  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
end

app/models/content.rb
class Content < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  # acts_as_commentable
  attr_accessible :user_id, :theme_id, :card_id, :category_id, :title, :country, :note, :position
  
  has_many :contributers, :source => :user
  
  belongs_to :theme
  belongs_to :user
  belongs_to :category
  belongs_to :card

  alias_method :author, :user
  def author_id; user_id; end
  
  # has_attached_file :image,
  #     :default_url => "/images/#{I18n.t(:app).downcase}/b-userpic/noavatar-:style.jpg",
  #     :path => "public/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :url => "/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :default_style => :medium,
  #     :styles => {
  #       :original => "600x600>",
  #       :medium => "140x140#", 
  #       :teaser => "64x64#",
  #       :game   => "48x48#", 
  #       :forum  => "32x32#",
  #       :chat   => "24x24#",
  #       :tiny   => "16x16#"
  #     }
      
  validates_presence_of :title
  validates_presence_of :user_id
  validates_presence_of :theme_id
  validates_presence_of :card_id
  validates_presence_of :category_id

  #scope :viewable, :conditions => "theme.state = 'published'"

  #accepts_nested_attributes_for :comment

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  respond_to :html, :xml
  before_filter :authenticate_user!
  
  #before_filter :login_required

  # GET /contents
  # GET /contents.xml
  def index
    @contents = Content.all

    respond_with @contents
  end

  # GET themes/contents/1
  # GET themes/contents/1.xml
  def show
    @content = Content.find(params[:id])

    respond_with @content

  # @contents = Content.all

  # respond_with @content
  end

  # GET themes/contents/new
  # GET themes/contents/new.xml
  def new
    @theme = Theme.find(params[:theme_id])
    @card = Card.find(params[:card_id])
    @content = @card.contents.build

    respond_with @content
  end

  # GET themes/contents/1/edit
  def edit
    @theme = Theme.find(params[:theme_id])
    @content = @theme.card.contents.find(params[:id])
  end

  # POST themes/contents
  # POST themes/contents.xml
  def create
    @theme = Theme.find(params[:theme_id])
    @card = Card.find(params[:card_id])
    @category = Category.find(params[:content_id])
    @content = @card.contents.build(params[:content])
    @content.user_id = current_user

    if @content.save
      flash[:notice] = "Content was successfully created."
    end

    respond_with @card
  end

  # PUT themes/contents/1
  # PUT themes/contents/1.xml
  def update
    @content = Content.find(params[:id])


    if @content.update_attributes(@content)
      format.html { redirect_to [@theme, @content], notice: 'Content was successfully updated.' }
    end

  end

  # DELETE themes/contents/1
  # DELETE themes/contents/1.xml
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_with @theme
  end


 # def toggle_close
 #   if current_user.admin?
 #     discussion = ForumDiscussion.find(params[:id])
 #     if discussion.closed?
 #       discussion.reopen!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde wieder geöffnet."
 #     elsif discussion.published?
 #       discussion.close!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde geschlossen."
 #     end
 #   else
 #     flash[:warning] = "Diskussion '#{discussion.subject}' darfst Du nicht schliessen."
 #   end
 #   redirect_to :back
 # end

  
  #def set_title
   # @title = "#{I18n.t(:game)}-Forum: "
#    @description = "Im Sauspiel Forum tauschen sich die Schafkopfer über die besten Spielstrategien und ihre schönsten Spiele aus, oder ratschen miteinander."
 # end
  
  #load_namespaced_extensions

end

app/views/contents/_form.html.erb
<%= simple_form_for(@content, :url=>theme_card_contents_path(@theme, @card)) do |f| %>
  
  <%= f.input :title, :label => "Inhalt", :input_html => { :class => "span2.5" } %>
  <%= f.input :position, :label => "Position" %>
  <%= f.input :card_id, :label => "Karten-ID" %>
  <%= f.input :category_id, :collection => @categories %>
  <%= f.input :theme_id, :label => "Thema" %>
  <%= f.submit "Inhalt anlegen", :class => "primary" %>
<% end %>

app/views/contents/edit.html.erb
<%= simple_form_for(@card, :url=>theme_card_path(@theme)) do |f| %>
  
  <%= f.input :title, :label => "Kartenname", :input_html => { :class => "span4" } %>
  <%= f.input :user_id, :label => "Autor" %>
  <%= f.input :theme_id, :label => "Thema" %>
  <%= f.submit "Änderung speichern", :class => "primary" %>
<% end %>

app/views/contents/index.html.erb
<h4>Karten</h4> 

<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.cards.each do |card| %>
        <tr>
          <td><%= card.position %></td>
          <td><%= link_to card.title, theme_card_path(@theme, card) %></td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Neue Karte anlegen', new_theme_card_path(@theme, @card), :class => 'btn large primary' %>

app/views/contents/new.html.erb
<h3>Neuen Inhalt eingeben</h3>

<%= render 'form' %>

<%= link_to raw('&larr; Zurück zur Übersicht'), theme_card_path(@theme, @card) %>

app/views/contents/show.html.erb
<h4>
  <%= @content.title %>
</h4>