config/routes.rb
Supertramp::Application.routes.draw do
  
  authenticated :user do
    root :to => 'themes#index'
  end


  resources :themes do
    resources :categories do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
    end

    resources :cards do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
      resources :content do
        match 'themes/:theme_id/cards/card_id/contents/:id' => 'contents#update', :via => :put, :as => :update_theme_card_contents
      end
    end

  end

    
    
    
  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  #acts_as_commentable

  attr_accessible :title, :user_id, :description, :public
  
  has_many :cards
  has_many :categories
  has_many :contributers, :source => :user
  has_many :theme_watches
  
  belongs_to :user
  alias_method :author, :user
  def author_id; user_id; end
  
  # has_attached_file :image,
  #     :default_url => "/images/#{I18n.t(:app).downcase}/b-userpic/noavatar-:style.jpg",
  #     :path => "public/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :url => "/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :default_style => :medium,
  #     :styles => {
  #       :original => "600x600>",
  #       :medium => "140x140#", 
  #       :teaser => "64x64#",
  #       :game   => "48x48#", 
  #       :forum  => "32x32#",
  #       :chat   => "24x24#",
  #       :tiny   => "16x16#"
  #     }
      
  validates_presence_of :title, :message => "Bitte gib einen Titel an."
  validates_presence_of :user_id, :message => "Ein Thema kann nicht ohne einen Benutzer angelegt werden."

  scope :viewable, :conditions => "themes.state = 'published'"

  accepts_nested_attributes_for :cards, :categories

  # aasm_column :state
  # aasm_initial_state :published
  # aasm_state :published
  # aasm_state :closed
  # aasm_state :hidden

  # aasm_event :hide do
  #   transitions :from => [:published, :closed], :to => :hidden
  # end
  # aasm_event :close do
  #   transitions :from => :published, :to => :closed
  # end
  # aasm_event :reopen do
  #   transitions :from => :closed, :to => :published
  # end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  respond_to :html, :xml

  before_filter :authenticate_user!
  #before_filter :login_required

  # GET /themes
  # GET /themes.xml
  def index
    @themes = Theme.all

    respond_with @themes
  end

  # GET /themes/1
  # GET /themes/1.xml
  def show
    @theme = Theme.find(params[:id])

    respond_with @theme

  # @cards = Card.all

  # respond_with @card
  end

  # GET /themes/new
  # GET /themes/new.xml
  def new
    @theme = Theme.new


    respond_with @theme
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
  end

  # POST /themes
  # POST /themes.xml
  def create
    @theme = Theme.new(params[:theme])
    @theme.user_id = current_user

    if @theme.save
      flash[:notice] = "Theme was successfully created."
    end

    respond_with @theme
  end

  # PUT /themes/1
  # PUT /themes/1.xml
  def update
    @theme = Theme.find(params[:id])

    if @theme.update_attributes(params[:theme])
      flash[:notice] = "Theme was successfully updated."
    end

    respond_with @theme
  end

  # DELETE /themes/1
  # DELETE /themes/1.xml
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy

    respond_with @theme
  end


 # def toggle_close
 #   if current_user.admin?
 #     discussion = ForumDiscussion.find(params[:id])
 #     if discussion.closed?
 #       discussion.reopen!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde wieder geöffnet."
 #     elsif discussion.published?
 #       discussion.close!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde geschlossen."
 #     end
 #   else
 #     flash[:warning] = "Diskussion '#{discussion.subject}' darfst Du nicht schliessen."
 #   end
 #   redirect_to :back
 # end

  
  #def set_title
   # @title = "#{I18n.t(:game)}-Forum: "
#    @description = "Im Sauspiel Forum tauschen sich die Schafkopfer über die besten Spielstrategien und ihre schönsten Spiele aus, oder ratschen miteinander."
 # end
  
  #load_namespaced_extensions

end

app/views/themes/_card.html.erb
<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.cards.each do |card| %>
        <tr>
          <td><%= card.position %></td>
          <td><%= link_to card.title, theme_card_path(@theme, card) %></td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/themes/_category.html.erb
<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.categories.each do |category| %>
        <tr>
          <td><%= category.position %></td>
          <td><%= link_to category.title, theme_category_path(@theme, category) %></td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/themes/_form.html.erb
<%= simple_form_for @theme do |f| %>
  
  <%= f.input :title, :label => "Themenname", :input_html => { :class => "span4" } %>
  <%= f.input :description, :label => "Beschreibung", :input_html => { :class => "span10" } %>
  <%= f.input :public, :label => "öffentlich" %>
  <%= f.submit "Thema anlegen", :class => "primary" %>
<% end %>

app/views/themes/edit.html.erb
<%= simple_form_for @theme do |f| %>
  
  <%= f.input :title, :label => "Themenname", :input_html => { :class => "span4" } %>
  <%= f.input :description, :label => "Beschreibung", :input_html => { :class => "span10" } %>
  <%= f.input :public, :label => "öffentlich" %>
  <%= f.input :user_id, :label => "Autor" %>
  <%= f.submit "Änderung speichern", :class => "primary" %>
<% end %>

app/views/themes/index.html.erb
<h4>Themen</h4> 

<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.position %></td>
        <td><%= link_to theme.title, theme %></td>     
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Neues Thema anlegen', new_theme_path, :class => 'btn large primary' %>

app/views/themes/new.htlm.erb
<header>
  <p>Neues Thema</p>
</header>

<%= render 'form' %>

<%= link_to raw('&larr; Zurück zur Übersicht'), themes_path %>

app/views/themes/new.html.erb
<h3>Neues Thema</h3>

<%= render 'form' %>

<%= link_to raw('&larr; Zurück zur Übersicht'), themes_path %>

app/views/themes/show.html.erb
<h4><%= @theme.title %>  <%= link_to '(Thema bearbeiten)', edit_theme_path %></h4>

  
<p>
  <%= render 'category' %>
  <%= link_to 'Neue Kategorie anlegen', new_theme_category_path(@theme, @category), :class => 'btn large primary' %>
</p>
</br>
<p>  
<%= render 'card' %>
<%= link_to 'Neue Karte anlegen', new_theme_card_path(@theme, @card), :class => 'btn large primary' %>
</p>