config/routes.rb
Supertramp::Application.routes.draw do
  
  authenticated :user do
    root :to => 'themes#index'
  end


  resources :themes do
    resources :categories do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
    end

    resources :cards do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
      resources :content do
        match 'themes/:theme_id/cards/card_id/contents/:id' => 'contents#update', :via => :put, :as => :update_theme_card_contents
      end
    end

  end

    
    
    
  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
end

app/models/card.rb
class Card < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  # acts_as_commentable
  attr_accessible :user_id, :theme_id, :title, :country, :note, :position
  
  has_many :images
  has_many :categories
  has_many :contents
  has_many :contributers, :source => :user
  

  belongs_to :theme
  belongs_to :user
  alias_method :author, :user
  def author_id; user_id; end
  
  # has_attached_file :image,
  #     :default_url => "/images/#{I18n.t(:app).downcase}/b-userpic/noavatar-:style.jpg",
  #     :path => "public/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :url => "/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :default_style => :medium,
  #     :styles => {
  #       :original => "600x600>",
  #       :medium => "140x140#", 
  #       :teaser => "64x64#",
  #       :game   => "48x48#", 
  #       :forum  => "32x32#",
  #       :chat   => "24x24#",
  #       :tiny   => "16x16#"
  #     }
      
  validates_presence_of :title
  validates_presence_of :user_id
  validates_presence_of :theme_id

  scope :viewable, :conditions => "themes.state = 'published'"

  accepts_nested_attributes_for :contents, :categories, :images

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  respond_to :html, :xml
  before_filter :authenticate_user!
  #before_filter :login_required

  # GET /cards
  # GET /cards.xml
  def index
    @cards = Card.all
    @theme = Theme.find(params[:theme_id])


    respond_with @cards
  end

  # GET themes/cards/1
  # GET themes/cards/1.xml
  def show
    @theme = Theme.find(params[:theme_id])
    @card = @theme.cards.find(params[:id])

    respond_with @card

  # @cards = Card.all

  # respond_with @card
  end

  # GET themes/cards/new
  # GET themes/cards/new.xml
  def new
    @theme = Theme.find(params[:theme_id])
    @card = @theme.cards.build

    respond_with @card
  end

  # GET themes/cards/1/edit
  def edit
    @theme = Theme.find(params[:theme_id])
    @card = @theme.cards.find(params[:id])
  end

  # POST themes/cards
  # POST themes/cards.xml
  def create
    @theme = Theme.find(params[:theme_id])
    @card = @theme.cards.build(params[:card])
    @card.user_id = current_user

    if @card.save
      flash[:notice] = "Card was successfully created."
    end

    respond_with @theme
  end

  # PUT themes/cards/1
  # PUT themes/cards/1.xml
  def update
    @theme = Theme.find(params[:theme_id])
    @card = @theme.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
      format.html { redirect_to @theme, notice: 'Card was successfully updated.' }
      format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end


    # def update
    # @gallery = Gallery.find(params[:gallery_id])
    # @photo = Photo.find(params[:id])
    # 
    # respond_to do |format|
    # if @photo.update_attributes(params[:photo])
      # format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
      # format.json { head :ok }
    # else
      # format.html { render action: "edit" }
      # format.json { render json: @photo.errors, status: :unprocessable_entity }
    # end

  end

  # DELETE themes/cards/1
  # DELETE themes/cards/1.xml
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_with @theme
  end


 # def toggle_close
 #   if current_user.admin?
 #     discussion = ForumDiscussion.find(params[:id])
 #     if discussion.closed?
 #       discussion.reopen!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde wieder geöffnet."
 #     elsif discussion.published?
 #       discussion.close!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde geschlossen."
 #     end
 #   else
 #     flash[:warning] = "Diskussion '#{discussion.subject}' darfst Du nicht schliessen."
 #   end
 #   redirect_to :back
 # end

  
  #def set_title
   # @title = "#{I18n.t(:game)}-Forum: "
#    @description = "Im Sauspiel Forum tauschen sich die Schafkopfer über die besten Spielstrategien und ihre schönsten Spiele aus, oder ratschen miteinander."
 # end
  
  #load_namespaced_extensions

end

app/views/cards/_form.html.erb
<%= simple_form_for(@card, :url=>theme_cards_path(@theme)) do |f| %>
  
  <%= f.input :title, :label => "Kartenname", :input_html => { :class => "span4" } %>
  <%= f.submit "Karte anlegen", :class => "primary" %>
<% end %>

app/views/cards/index.html.erb
<h4>Karten</h4> 

<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.cards.each do |card| %>
        <tr>
          <td><%= card.position %></td>
          <td><%= link_to card.title, theme_card_path(@theme, card) %></td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Neue Karte anlegen', new_theme_card_path(@theme, @card), :class => 'btn large primary' %>

app/views/cards/show.html.erb
<h4>
  <%= @card.title %>
</h4>
<%= link_to 'Karte bearbeiten', edit_theme_card_path %>

<div class="well">  
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.categories.each do |category| %>
        <tr>
          <td>#<%= category.position %></td>
          <td>ID-<%= category.id %></td>
          <td><%= link_to category.title, new_theme_card_content_path(@theme, @card, @content) %></td>
          <td><%= link_to 'bearbeiten',  edit_theme_category_path(@theme, category) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @card.contents.each do |content| %>
        <tr>
          <td>Wert: <%= content.title %></td>
          <td><%= link_to 'Bearbeiten',  edit_theme_card_content_path(@theme, @card, content) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  
</div>
<%= link_to 'Neue Kategorie anlegen', new_theme_category_path(@theme, @category), :class => 'btn large primary' %>
<%= link_to 'Neuen Inhalt hinzufügen', new_theme_card_content_path(@theme, @card, @content), :class => 'btn large primary' %>