config/routes.rb
Supertramp::Application.routes.draw do
  
  authenticated :user do
    root :to => 'themes#index'
  end


  resources :themes do
    resources :categories do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
    end

    resources :cards do
      match 'themes/:theme_id/cards/:id' => 'cards#update', :via => :put, :as => :update_theme_cards
      resources :content do
        match 'themes/:theme_id/cards/card_id/contents/:id' => 'contents#update', :via => :put, :as => :update_theme_card_contents
      end
    end

  end

    
    
    
  devise_scope :user do
    root :to => "devise/registrations#new"
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  match 'users/bulk_invite/:quantity' => 'users#bulk_invite', :via => :get, :as => :bulk_invite
  resources :users, :only => [:show, :index] do
    get 'invite', :on => :member
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :title, :use => :slugged
  
  # acts_as_commentable
  
  has_many :cards
  has_many :contents
  has_many :contributers, :source => :user
  has_many :comments

  belongs_to :creator, :class_name => "User"
  belongs_to :theme
  
  # has_attached_file :image,
  #     :default_url => "/images/#{I18n.t(:app).downcase}/b-userpic/noavatar-:style.jpg",
  #     :path => "public/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :url => "/uploads/:class/:attachment/:id_partition/:style/:basename.:extension",
  #     :default_style => :medium,
  #     :styles => {
  #       :original => "600x600>",
  #       :medium => "140x140#", 
  #       :teaser => "64x64#",
  #       :game   => "48x48#", 
  #       :forum  => "32x32#",
  #       :chat   => "24x24#",
  #       :tiny   => "16x16#"
  #     }
      
  validates_presence_of :title
  validates_presence_of :user_id
  validates_presence_of :theme_id

  accepts_nested_attributes_for :contents

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  respond_to :html, :xml
  before_filter :authenticate_user!  
  #before_filter :login_required

  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all
    @theme = Theme.find(params[:theme_id])


    respond_with @categories
  end

  # GET themes/categories/1
  # GET themes/categories/1.xml
  def show
    @theme = Theme.find(params[:theme_id])
    @category = @theme.categories.find(params[:id])

    respond_with @category

  # @categories = Category.all

  # respond_with @category
  end

  # GET themes/categories/new
  # GET themes/categories/new.xml
  def new
    @theme = Theme.find(params[:theme_id])
    @category = @theme.categories.build

    respond_with @category
  end

  # GET themes/categories/1/edit
  def edit
    @theme = Theme.find(params[:theme_id])
    @category = @theme.categories.find(params[:id])
  end

  # POST themes/categories
  # POST themes/categories.xml
  def create
    @theme = Theme.find(params[:theme_id])
    @category = @theme.categories.build(params[:category])
    @category.user_id = current_user

    if @category.save
      flash[:notice] = "Category was successfully created."
    else
      flash[:error] = "Category could not be created."
    end

    respond_with @theme
  end

  # PUT themes/categories/1
  # PUT themes/categories/1.xml
  def update
    @theme = Theme.find(params[:theme_id])
    @category = @theme.categories.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
      format.html { redirect_to @theme, notice: 'Category was successfully updated.' }
      format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE themes/categories/1
  # DELETE themes/categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_with @theme
  end


 # def toggle_close
 #   if current_user.admin?
 #     discussion = ForumDiscussion.find(params[:id])
 #     if discussion.closed?
 #       discussion.reopen!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde wieder geöffnet."
 #     elsif discussion.published?
 #       discussion.close!
 #       flash[:success] = "Diskussion '#{discussion.subject}' wurde geschlossen."
 #     end
 #   else
 #     flash[:warning] = "Diskussion '#{discussion.subject}' darfst Du nicht schliessen."
 #   end
 #   redirect_to :back
 # end

  
  #def set_title
   # @title = "#{I18n.t(:game)}-Forum: "
#    @description = "Im Sauspiel Forum tauschen sich die Schafkopfer über die besten Spielstrategien und ihre schönsten Spiele aus, oder ratschen miteinander."
 # end
  
  #load_namespaced_extensions

end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, :url=>theme_categories_path(@theme)) do |f| %>
  
  <%= f.input :title, :label => "Kategoriename", :input_html => { :class => "span4" } %>
  
  <%= f.submit "Kategorie anlegen", :class => "primary" %>
<% end %>

app/views/categories/edit.html.erb
<%= simple_form_for(@category, :url=>theme_category_path(@theme)) do |f| %>
  
  <%= f.input :title, :label => "Kategoriename", :input_html => { :class => "span4" } %>
  <%= f.input :position, :label => "Position" %>
  <%= f.submit "Änderung speichern", :class => "primary" %>
<% end %>

app/views/categories/index.html.erb
<h4>Kategorien</h4> 

<div class="well">
  <table class="bordered-table zebra-striped">
    <tbody>
      <% @theme.categories.each do |category| %>
        <tr>
          <td><%= category.position %></td>
          <td><%= link_to category.title, theme_category_path(@theme, category) %></td>     
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Neue Karte anlegen', new_theme_category_path(@theme, @category), :class => 'btn large primary' %>

app/views/categories/new.html.erb
<h3>Neue Kategorie anlegen</h3>

<%= render 'form' %>

<%= link_to raw('&larr; Zurück zur Übersicht'), theme_categories_path(@theme) %>

app/views/categories/show.html.erb
<h4>
  <%= @category.title %>
</h4>
<%= link_to 'Kategorie bearbeiten', edit_theme_category_path %>